package scan_test

import (
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"
	"testing"

	"github.com/rigfile/rigfile/internal/scan"
	"github.com/rigfile/rigfile/internal/scan/corpus"
)

var update = flag.Bool("update", false, "rewrite docs/scanner-metrics.md")

const (
	corpusSeed   = 20260925
	reportPath   = "../../docs/scanner-metrics.md"
	maxFPRatePct = 1.0 // owner decision O2
	strictFamily = "strict"
	coreTier     = "core"
	stretchTier  = "stretch"
)

type famStat struct {
	n, hit int
	rules  map[string]int
	misses []string
}

func TestCorpusRecallAndFalsePositives(t *testing.T) {
	sc, err := scan.New(scan.Options{SkipNames: true}) // content only: names are measured separately
	if err != nil {
		t.Fatal(err)
	}
	samples := corpus.All(corpusSeed)

	pos := map[string]*famStat{}
	var famOrder []string
	tiers := map[string]string{}
	neg := map[string]*famStat{}
	var negOrder []string
	var negTotal, negFP int
	var coreN, coreHit int
	fpRules := map[string]int{}
	var fpList []string
	strictFP := 0

	for _, s := range samples {
		fs := sc.ScanFile(s.Path, []byte(s.Content))
		if s.Positive {
			st := pos[s.Family]
			if st == nil {
				st = &famStat{rules: map[string]int{}}
				pos[s.Family] = st
				famOrder = append(famOrder, s.Family)
				tiers[s.Family] = s.Tier
			}
			st.n++
			if len(fs) > 0 {
				st.hit++
				seen := map[string]bool{}
				for _, f := range fs {
					if !seen[f.RuleID] {
						seen[f.RuleID] = true
						st.rules[f.RuleID]++
					}
				}
			} else {
				st.misses = append(st.misses, s.ID)
			}
			if s.Tier == coreTier {
				coreN++
				if len(fs) > 0 {
					coreHit++
				}
			}
			continue
		}
		st := neg[s.Family]
		if st == nil {
			st = &famStat{rules: map[string]int{}}
			neg[s.Family] = st
			negOrder = append(negOrder, s.Family)
		}
		st.n++
		negTotal++
		if len(fs) > 0 {
			st.hit++
			negFP++
			for _, f := range fs {
				fpRules[f.RuleID]++
			}
			fpList = append(fpList, s.ID)
			if s.Tier == strictFamily {
				strictFP++
			}
		}
	}

	report := renderReport(pos, famOrder, tiers, neg, negOrder, negTotal, negFP, fpRules, fpList, coreN, coreHit, names(t))
	if *update {
		if err := os.WriteFile(reportPath, []byte(report), 0o644); err != nil {
			t.Fatal(err)
		}
	} else if old, err := os.ReadFile(reportPath); err != nil || string(old) != report {
		t.Errorf("%s is stale or missing: run `go test ./internal/scan -run TestCorpus -update` and review the diff", reportPath)
	}

	// ---- gates
	for _, fam := range famOrder {
		if tiers[fam] == coreTier && pos[fam].hit != pos[fam].n {
			t.Errorf("recall < 100%% for core family %s: missed %v", fam, pos[fam].misses)
		}
	}
	if coreHit != coreN {
		t.Errorf("core recall %d/%d", coreHit, coreN)
	}
	if rate := 100 * float64(negFP) / float64(negTotal); rate > maxFPRatePct {
		t.Errorf("false-positive rate %.2f%% (%d of %d) exceeds %.1f%%; offenders: %v (rules %v)", rate, negFP, negTotal, maxFPRatePct, fpList, fpRules)
	}
	if strictFP != 0 {
		t.Errorf("%d false positives in the strict (.env.example) class", strictFP)
	}
	t.Logf("core recall %d/%d, stretch families reported, FP %d/%d", coreHit, coreN, negFP, negTotal)
}

func TestCorpusIsDeterministicAndContainsNoRealisticSecretInSource(t *testing.T) {
	a, b := corpus.All(corpusSeed), corpus.All(corpusSeed)
	if len(a) != len(b) {
		t.Fatal("length differs")
	}
	for i := range a {
		if a[i] != b[i] {
			t.Fatalf("sample %s differs between runs", a[i].ID)
		}
	}
	if len(a) < 500 {
		t.Fatalf("corpus too small for a 1%% threshold to mean anything: %d samples", len(a))
	}
}

// names returns (blockedOK, blockedTotal, allowedOK, allowedTotal, problems).
type nameResult struct {
	blockedOK, blockedN, allowedOK, allowedN int
	bad                                      []string
}

func names(t *testing.T) nameResult {
	t.Helper()
	var r nameResult
	for _, c := range corpus.Names() {
		flagged := scan.IsSensitiveFilename(c.Path)
		if c.Blocked {
			r.blockedN++
			if flagged {
				r.blockedOK++
			} else {
				r.bad = append(r.bad, "not blocked: "+c.Path)
			}
		} else {
			r.allowedN++
			if !flagged {
				r.allowedOK++
			} else {
				r.bad = append(r.bad, "wrongly blocked: "+c.Path)
			}
		}
	}
	for _, b := range r.bad {
		t.Error(b)
	}
	return r
}

func renderReport(pos map[string]*famStat, famOrder []string, tiers map[string]string, neg map[string]*famStat, negOrder []string,
	negTotal, negFP int, fpRules map[string]int, fpList []string, coreN, coreHit int, nr nameResult) string {
	var b strings.Builder
	rules, _ := scan.DefaultRuleset()
	fmt.Fprintf(&b, "# Scanner metrics (generated: do not edit)\n\n")
	fmt.Fprintf(&b, "Generated by `go test ./internal/scan -run TestCorpus -update` from `internal/scan/corpus` (seed %d). Rules: gitleaks %s (%d rules) plus Rigfile additions. Content-only (file names are measured separately). No sample value appears here.\n\n", corpusSeed, scan.RulesVersion(), rules.NumRules())
	fmt.Fprintf(&b, "## Summary\n\n| Metric | Result | Gate |\n|---|---|---|\n")
	fmt.Fprintf(&b, "| Core recall | %d / %d (%.1f%%) | 100%% |\n", coreHit, coreN, 100*float64(coreHit)/float64(coreN))
	stN, stHit := 0, 0
	for _, f := range famOrder {
		if tiers[f] == stretchTier {
			stN += pos[f].n
			stHit += pos[f].hit
		}
	}
	if stN > 0 {
		fmt.Fprintf(&b, "| Stretch recall | %d / %d | reported, not gated |\n", stHit, stN)
	}
	fmt.Fprintf(&b, "| False positives on hard negatives | %d / %d (%.2f%%) | <= %.1f%% |\n", negFP, negTotal, 100*float64(negFP)/float64(negTotal), maxFPRatePct)
	fmt.Fprintf(&b, "| File names blocked / look-alikes allowed | %d / %d and %d / %d | 100%% |\n\n", nr.blockedOK, nr.blockedN, nr.allowedOK, nr.allowedN)

	fmt.Fprintf(&b, "## Positives by family\n\n| Family | Tier | Detected | Rules that fired |\n|---|---|---|---|\n")
	for _, f := range famOrder {
		st := pos[f]
		var rs []string
		for r, n := range st.rules {
			rs = append(rs, fmt.Sprintf("%s (%d)", r, n))
		}
		sort.Strings(rs)
		fmt.Fprintf(&b, "| %s | %s | %d / %d | %s |\n", f, tiers[f], st.hit, st.n, strings.Join(rs, ", "))
	}
	fmt.Fprintf(&b, "\n## Hard negatives by family\n\n| Family | Samples | False positives |\n|---|---|---|\n")
	for _, f := range negOrder {
		fmt.Fprintf(&b, "| %s | %d | %d |\n", f, neg[f].n, neg[f].hit)
	}
	if negFP > 0 {
		var rs []string
		for r, n := range fpRules {
			rs = append(rs, fmt.Sprintf("%s (%d)", r, n))
		}
		sort.Strings(rs)
		sort.Strings(fpList)
		fmt.Fprintf(&b, "\nFalse positives by rule: %s\n\nSamples: %s\n", strings.Join(rs, ", "), strings.Join(fpList, ", "))
	}
	return b.String()
}
